FROM node:18 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM tomcat:9-jdk21
RUN rm -rf /usr/local/tomcat/webapps/*
COPY --from=build-stage /app/dist /usr/local/tomcat/webapps/ROOT
EXPOSE 2026
CMD ["catalina.sh", "run"]