
services:
  db:
    image: mysql:8.0
    container_name: vote-db
    restart: always
    environment:
      MYSQL_DATABASE: online_voting_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - vote-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.yml
    container_name: vote-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/online_voting_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "2027:8080"   # host:container
    networks:
      - vote-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.yml
    container_name: vote-frontend
    restart: always
    ports:
      - "2026:8080"
    depends_on:
      - backend
    networks:
      - vote-net

volumes:
  db_data:

networks:
  vote-net:
    driver: bridge
